# Generate data for weight time series assignment
I'm going to generate a dataset that contains the weight of twenty inviduals over six weeks. Half will be male and weigh more than the other half which will be female. I also want half of the people to gain weight and the other half to loose it.

In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Weight data

In [73]:
"""Parameters"""
# Select mean weight of each sex
means = {'male': 170, 'female': 140}

# We'll handle each sex separately. Note: we could sample from multiple means at once, but this does not generalize
#to groups of different sizes (like if we had different numbers of male and female)
df = pd.DataFrame()
for sex in ['male', 'female']:
    """Initalize data"""
    # Seed for reproducibility
    np.random.seed(123)
    # Sample from 60 sample from a normal distribution where person X weeks
    data = np.random.normal(means[sex], 2.5, (10, 6))

    """Introduce trend"""
    # Let's have some people loose weight while some people gain weight
    # We will sample weight fluctuations and then assign half of the people to lose and the other half to gain
    np.random.seed(123)
    fluctuations = np.abs(np.random.normal(2, .5, (10, 6)))
    # alternate gains and losses
    direction = np.array([1, -1] * 5)
    # Take a look at this variable and you will see that each row alternates +/-
    weighted_flux = direction.reshape(-1, 1) * fluctuations
    # Now let's do a cumulative sum to create a trend (add up the fluctuations from week to week)
    cumulative_flux = weighted_flux.cumsum(1)

    """Combine flux with initial"""
    # `wink`
    sex_data = data + cumulative_flux
    sex_df = pd.DataFrame(sex_data, columns=[f'Week_{x}' for x in range(data.shape[1])])
    sex_df['sex'] = sex
    df = pd.concat([df, sex_df])
df['person'] = [f'P{x}' for x in range(df.shape[0])]
df = df.set_index(['person', 'sex'])
df

,,Week_0,Week_1,Week_2,Week_3,Week_4,Week_5
person,sex,,,,,,
P0,male,168.743108,176.449221,176.804793,173.578463,177.608399,186.009209
P1,male,163.146642,166.355514,167.959668,161.061347,159.870426,159.378223
P2,male,176.474169,172.828989,175.094298,176.901199,186.604867,189.650401
P3,male,170.008108,166.270346,164.779617,163.917660,156.319162,159.010405
P4,male,168.238358,171.459805,177.775500,173.221694,178.373190,178.138097
P5,male,167.488761,160.530631,161.984038,163.013116,164.617734,159.951807
P6,male,172.008538,176.066091,173.706925,178.756648,177.631480,176.461888
P7,male,167.218200,167.343062,164.585725,161.715591,164.529898,157.374809
P8,male,174.936208,181.203798,173.726184,175.845032,185.673140,180.919671
P9,male,168.059366,168.123790,165.231913,164.514920,161.118992,157.518667
P10,female,138.743108,146.449221,146.804793,143.578463,147.608399,156.009209
P11,female,133.146642,136.355514,137.959668,131.061347,129.870426,129.378223
P12,female,146.474169,142.828989,145.094298,146.901199,156.604867,159.650401
P13,female,140.008108,136.270346,134.779617,133.917660,126.319162,129.010405
P14,female,138.238358,141.459805,147.775500,143.221694,148.373190,148.138097
P15,female,137.488761,130.530631,131.984038,133.013116,134.617734,129.951807
P16,female,142.008538,146.066091,143.706925,148.756648,147.631480,146.461888
P17,female,137.218200,137.343062,134.585725,131.715591,134.529898,127.374809
P18,female,144.936208,151.203798,143.726184,145.845032,155.673140,150.919671
P19,female,138.059366,138.123790,135.231913,134.514920,131.118992,127.518667

# Metadata